apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: gateway
  name: gateway
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gateway
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: gateway
    spec:
      containers:
      - image: spring-6-gateway:k8s
        name: spring-6-gateway
        env:
          - name: SPRING_PROFILES_ACTIVE
            value: docker
        resources: {}
status: {}
