apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: mysql-service
  name: mysql-service
spec:
  type: ClusterIP
  ports:
  - name: 3008-3006
    port: 3008
    protocol: TCP
    targetPort: 3006
  selector:
    app: mysql
status:
  loadBalancer: {}
