services:
  mysql-8.0:
    image: mysql:8.0
    container_name: mysql-8.0-jt
    environment:
      MYSQL_ROOT_PASSWORD: Galerien3?
      MYSQL_USER: restdadmin
      MYSQL_PASSWORD: restadmin
      MYSQL_DATABASE: restdb
    volumes:
      - mysql-8.0:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "3309:3306"
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 30s
      timeout: 10s
      retries: 5

  mongo-jt:
    image: mongo:latest
    container_name: mongo-jt
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: Galerien3?
    ports:
      - "27017:27017"

  auth-server:
    image: pierrotadesso/spring-6-auth-server:sb344sec49
    container_name: auth-server-jt
    ports:
      - "9000:9000"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/actuator/health"]
      interval: 30s
      timeout: 10s
      retries: 5

  rest-mvc:
    image: pierrotadesso/spring-6-rest-mvc:sb344sec49
    container_name: rest-mvc-jt
    environment:
      SPRING_PROFILES_ACTIVE: localmysql
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql-8.0-jt:3306/restdb
      SPRING_DATASOURCE_USERNAME: restdadmin
      SPRING_SECURITY_OAUTH2_RESOURCESERVER_JWT_ISSUER_URI: http://auth-server-jt:9000
      SERVER_PORT: 8080
    ports:
      - "8080:8080"
    depends_on:
        mysql-8.0:
            condition: service_healthy
        auth-server:
            condition: service_healthy
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8080/actuator/health" ]
      interval: 30s
      timeout: 10s
      retries: 5

  gateway:
    image: pierrotadesso/spring-6-gateway:sb344sec49
    container_name: gateway-jt
    environment:
      SPRING_PROFILES_ACTIVE: docker
      SPRING_SECURITY_OAUTH2_RESOURCESERVER_JWT_ISSUER_URI: http://auth-server-jt:9000
      SERVER_PORT: 8080
    ports:
      - "8080:8080"
    depends_on:
        rest-mvc:
            condition: service_healthy

volumes:
  mysql-8.0: